<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name=generator content="HydePHP">

    @stack('meta')

    <title>
        @if (isset($title))
        {{ config('hyde.name', 'HydePHP') }} - {{ $title }}
        @else
        {{ config('hyde.name', 'HydePHP') }}
        @endif
    </title>

    <!-- The compiled Tailwind styles generated by the app -->
    <link rel="stylesheet" href="{{ Hyde::relativePath('media/tailwind.css', $currentPage) }}">
    
    <!-- The main stylesheet generated by the app -->
    <link rel="stylesheet" href="{{ Hyde::relativePath('media/app.css', $currentPage) }}">

    @include('hyde::layouts.meta') 
</head>
<body id="app" class="flex flex-col min-h-screen overflow-x-hidden">
    @includeUnless($withoutNavigation ?? false, 'hyde::layouts.navigation') 

    <section id="content">
        @yield('content') 
    </section>

    @includeUnless(config('hyde.footer.enabled', true) && ($withoutNavigation ?? false), 'hyde::layouts.footer') 
</body>
</html>
